export const mockedGetCarsServiceList = [
  {
    id: 487,
    VIN: "36365563463535643",
    region: "Северная Америка",
    country: "Мексика",
    date: "19.010.2024",
    manufacturer: "Неизвестный производитель",
    vehicleAttributes:
      "Неизвестный тип кузова, Газовый, Неизвестный тип трансмиссии, Антипробуксовочная система",
    checkDigit: "4",
    modelYear: "2006",
    assemblyPlant: "Неизвестное место",
    serialNumber: "535643",
    nameMaster: "Виктор",
    problems: "",
  },
  {
    id: 488,
    VIN: "36365563463535643",
    region: "Северная Америка",
    country: "Мексика",
    date: "19.010.2024",
    manufacturer: "Неизвестный производитель",
    vehicleAttributes:
      "Неизвестный тип кузова, Газовый, Неизвестный тип трансмиссии, Антипробуксовочная система",
    checkDigit: "4",
    modelYear: "2006",
    assemblyPlant: "Неизвестное место",
    serialNumber: "535643",
    nameMaster: "Владимир",
    problems: "",
  },
  {
    id: 489,
    VIN: "36365563463535643",
    region: "Северная Америка",
    country: "Мексика",
    date: "19.010.2024",
    manufacturer: "Неизвестный производитель",
    vehicleAttributes:
      "Неизвестный тип кузова, Газовый, Неизвестный тип трансмиссии, Антипробуксовочная система",
    checkDigit: "4",
    modelYear: "2006",
    assemblyPlant: "Неизвестное место",
    serialNumber: "535643",
    nameMaster: "Данила",
    problems: "",
  },
];
