export const mockedGetCarsFinishList = [
  {
    nameMaster: "Василий",
    id: 488,
    VIN: "36365563463535643",
    region: "Северная Америка",
    country: "Мексика",
    manufacturer: "Неизвестный производитель",
    vehicleAttributes:
      "Неизвестный тип кузова, Газовый, Неизвестный тип трансмиссии, Антипробуксовочная система",
    checkDigit: "4",
    modelYear: "2003",
    assemblyPlant: "Неизвестное место",
    serialNumber: "535643",
    problems: "",
    date: "19.010.2024",
    recomm: "Рекомендации",
    workOncar: "Было заменено: масло, моторный двигатель",
  },
  {
    nameMaster: "Иван",
    id: 489,
    VIN: "36365563463535643",
    region: "Северная Америка",
    country: "Мексика",
    manufacturer: "Неизвестный производитель",
    vehicleAttributes:
      "Неизвестный тип кузова, Газовый, Неизвестный тип трансмиссии, Антипробуксовочная система",
    checkDigit: "4",
    modelYear: "2006",
    assemblyPlant: "Неизвестное место",
    serialNumber: "535643",
    problems: "",
    date: "19.010.2024",
    recomm: "Рекомендации",
    workOncar: "Было заменено: масло, моторный двигатель",
  },
  {
    nameMaster: "Сергей",
    id: 490,
    VIN: "36365563463535643",
    region: "Северная Америка",
    country: "Мексика",
    manufacturer: "Неизвестный производитель",
    vehicleAttributes:
      "Неизвестный тип кузова, Газовый, Неизвестный тип трансмиссии, Антипробуксовочная система",
    checkDigit: "4",
    modelYear: "2004",
    assemblyPlant: "Неизвестное место",
    serialNumber: "535643",
    problems: "",
    date: "19.010.2024",
    recomm: "Рекомендации",
    workOncar: "Было заменено: масло, моторный двигатель",
  },
];
